apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    image.redhat.com/generate: "true"
    appstudio.openshift.io/pac-provision: request
  name: serverless-openshift-knative-operator
spec:
  componentName: serverless-openshift-knative-operator
  application: serverless-operator-konflux
  source:
    git:
      url: https://github.com/openshift-knative/serverless-operator.git
      context:
      dockerfileUrl: openshift-knative-operator/Dockerfile
      revision: konflux
