apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: serverless-operator-konflux
spec:
  description: serverless-operator (konflux banch)
  displayName: serverless-operator (konflux branch)
